all:
	tectonic main.tex

xelatex:
	xelatex -interaction=nonstopmode main.tex
	xelatex -interaction=nonstopmode main.tex
	xelatex -interaction=nonstopmode main.tex

clean:
	rm -f *.aux *.log *.out *.toc *.lof *.lot *.fls *.fdb_latexmk *.synctex.gz chapters/*.aux appendices/*.aux
